mkdir output
mkdir output/mc
mkdir output/observables
mkdir output/observables/acf
mkdir output/observables/barrier
mkdir output/observables/barrier/channel
mkdir output/observables/barrier/coors
mkdir output/observables/barrier/psf
mkdir output/observables/nrgs
